import Foundation

/// Bridges Ghost Mode evening reflections and daily rituals into Plut0's sovereign Notes & Journal engine.
public enum GhostReflectionNoteBridge {

    /// Creates or updates a structured reflection note in the Journal repository for the given day.
    @discardableResult
    public static func createOrUpdateReflectionNote(
        date: Date = Date(),
        dayRecord: GhostDay,
        receipts: [GhostReceipt],
        rules: [GhostProtocolRule],
        morningIntention: String,
        eveningReflection: String
    ) async throws -> NoteID {
        let noteID = NoteID()
        let dateFormatter = DateFormatter()
        dateFormatter.dateFormat = "EEEE, MMMM d, yyyy"
        let dateString = dateFormatter.string(from: date)

        let title = "Ghost Reflection — \(dateString)"

        var blocks: [NoteBlock] = []

        // Heading
        blocks.append(.heading(HeadingBlock(text: title, level: 1)))

        // Quick KPI Status
        let bodyTag    = dayRecord.bodyClosed    ? "[✓] SEALED" : "[ ] OPEN"
        let mindTag    = dayRecord.mindClosed    ? "[✓] SEALED" : "[ ] OPEN"
        let silMinutes = dayRecord.silenceMinutesVerified + dayRecord.silenceMinutesAttested
        let silTag     = dayRecord.silenceClosed ? "[✓] SEALED (\(silMinutes)m)" : "[ ] OPEN (\(silMinutes)m)"

        blocks.append(.bullet(BulletBlock(text: "Body Ring: \(bodyTag)")))
        blocks.append(.bullet(BulletBlock(text: "Mind Ring: \(mindTag)")))
        blocks.append(.bullet(BulletBlock(text: "Silence Ring: \(silTag)")))
        blocks.append(.bullet(BulletBlock(text: "Day Score: \(dayRecord.score)/100 · Ghost Day: \(dayRecord.ghostDay ? "YES" : "NO")")))

        blocks.append(.divider(DividerBlock()))

        // Morning Intention
        if !morningIntention.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            blocks.append(.heading(HeadingBlock(text: "Morning Intention", level: 2)))
            blocks.append(.paragraph(ParagraphBlock(text: morningIntention)))
        }

        // Evening Synthesis
        if !eveningReflection.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            blocks.append(.heading(HeadingBlock(text: "Evening Reflection & Realization", level: 2)))
            blocks.append(.paragraph(ParagraphBlock(text: eveningReflection)))
        }

        // Protocol Receipts
        if !receipts.isEmpty {
            blocks.append(.heading(HeadingBlock(text: "Executed Protocol Receipts", level: 2)))
            let rulesMap = Dictionary(uniqueKeysWithValues: rules.map { ($0.id, $0) })
            for r in receipts {
                let ruleName = rulesMap[r.ruleID]?.title ?? "Rule"
                let valStr = r.valueReal.truncatingRemainder(dividingBy: 1) == 0 ? "\(Int(r.valueReal))" : String(format: "%.1f", r.valueReal)
                let timeStr = DateFormatter.localizedString(from: r.loggedAt, dateStyle: .none, timeStyle: .short)
                blocks.append(.checklistItem(ChecklistItemBlock(text: "\(ruleName): \(valStr) (logged at \(timeStr))", isChecked: true)))
            }
        }

        blocks.append(.divider(DividerBlock()))
        blocks.append(.paragraph(ParagraphBlock(text: "Auto-generated by Plut0 Ghost Mode OS.")))

        let content = NoteContent(version: 1, blocks: blocks)

        // Apply creation mutation to JournalDocumentEngine
        try await JournalDocumentEngine.shared.apply(NoteMutation.createNote(noteID: noteID, folderID: nil))
        try await JournalDocumentEngine.shared.apply(NoteMutation.setTitle(noteID: noteID, title: title))
        try await JournalDocumentEngine.shared.apply(NoteMutation.updateContent(noteID: noteID, content: content))
        try await JournalDocumentEngine.shared.apply(NoteMutation.setPrivate(noteID: noteID, isPrivate: true))

        // Link note to Ghost Day
        _ = try? await GhostEngine.shared.setReflectionNoteID(noteID.description, date: date)

        return noteID
    }
}
